import { Router } from 'express';
import draftController from '../controllers/DraftController';
import { authMiddleware } from '../middlewares/authMiddleware';

const router = Router();

// All draft routes are protected and require a valid user token
router.use(authMiddleware);

/**
 * @openapi
 * /api/drafts:
 *   get:
 *     summary: List all news drafts
 *     description: Retrieve all news drafts generated by OCR+LLM for the authenticated user.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: [PENDING, APPROVED, REJECTED]
 *         description: Optional status to filter drafts by.
 *     responses:
 *       200:
 *         description: A list of drafts.
 *       400:
 *         description: Invalid status provided.
 *       401:
 *         description: Unauthorized.
 */
router.get('/', draftController.getDrafts.bind(draftController));

/**
 * @openapi
 * /api/drafts/{id}:
 *   get:
 *     summary: Get draft details
 *     description: Retrieves details of a specific draft, including the original raw OCR text and the generated structured JSON content.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the draft to retrieve.
 *     responses:
 *       200:
 *         description: Draft details retrieved successfully.
 *       400:
 *         description: Invalid draft ID.
 *       401:
 *         description: Unauthorized.
 *       404:
 *         description: Draft not found or does not belong to user.
 */
router.get('/:id', draftController.getDraftById.bind(draftController));

/**
 * @openapi
 * /api/drafts/{id}:
 *   put:
 *     summary: Update draft content
 *     description: Updates the generated JSON content (titulo, resumo, fonte) of a specific draft. The input is sanitized to prevent XSS.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the draft to update.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - titulo
 *               - resumo
 *               - fonte
 *             properties:
 *               titulo:
 *                 type: string
 *               resumo:
 *                 type: string
 *               fonte:
 *                 type: string
 *     responses:
 *       200:
 *         description: Draft updated successfully.
 *       400:
 *         description: Invalid input or missing fields.
 *       401:
 *         description: Unauthorized.
 *       404:
 *         description: Draft not found or does not belong to user.
 */
router.put('/:id', draftController.updateDraft.bind(draftController));

/**
 * @openapi
 * /api/drafts/{id}/approve:
 *   post:
 *     summary: Approve a draft
 *     description: Marks the draft as APPROVED and queues it for bulk broadcasting to all active contacts.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the draft to approve.
 *     responses:
 *       200:
 *         description: Draft approved and queued for broadcasting.
 *       400:
 *         description: Invalid draft ID.
 *       401:
 *         description: Unauthorized.
 *       404:
 *         description: Draft not found or does not belong to user.
 */
router.post('/:id/approve', draftController.approveDraft.bind(draftController));

/**
 * @openapi
 * /api/drafts/{id}/reject:
 *   post:
 *     summary: Reject a draft
 *     description: Marks the draft as REJECTED. It will not be sent.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the draft to reject.
 *     responses:
 *       200:
 *         description: Draft rejected successfully.
 *       400:
 *         description: Invalid draft ID.
 *       401:
 *         description: Unauthorized.
 *       404:
 *         description: Draft not found or does not belong to user.
 */
router.post('/:id/reject', draftController.rejectDraft.bind(draftController));

/**
 * @openapi
 * /api/drafts/{id}/cancel:
 *   post:
 *     summary: Cancel a broadcast
 *     description: Interrupts an ongoing or pending broadcast, updating status to CANCELLED.
 *     tags: [Drafts]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the draft to cancel.
 *     responses:
 *       200:
 *         description: Broadcast cancelled successfully.
 *       400:
 *         description: Invalid draft ID.
 *       401:
 *         description: Unauthorized.
 *       404:
 *         description: Draft not found or does not belong to user.
 */
router.post('/:id/cancel', draftController.cancelDraft.bind(draftController));

export default router;
