import { PrismaClient, DraftStatus } from '@prisma/client';
import { NewsArticleJSON } from './NewsGeneratorService';
import sanitizeHtml from 'sanitize-html';
import { AppError } from '../utils/AppError';
import logger from '../utils/logger';
import contactService from './ContactService';
import { broadcastQueue, BROADCAST_QUEUE_NAME } from '../queues/broadcastQueue';

const prisma = new PrismaClient();

export class DraftService {
  /**
   * Persists a generated news draft in the database pending user review.
   *
   * @param userId - ID of the user who requested the generation.
   * @param originalText - The raw OCR text.
   * @param generatedContent - The structured JSON generated by the Llama model.
   * @returns The created Draft record.
   */
  async createDraft(userId: number, originalText: string, generatedContent: NewsArticleJSON, imagePath?: string) {
    return prisma.draft.create({
      data: {
        userId,
        originalText,
        generatedContent: generatedContent as any, // Typed as JSON in Prisma
        imagePath,
        status: DraftStatus.PENDING,
      },
    });
  }

  /**
   * Retrieves all drafts for a specific user, optionally filtered by status.
   */
  async getUserDrafts(userId: number, status?: DraftStatus) {
    return prisma.draft.findMany({
      where: { 
        userId,
        ...(status && { status }) 
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  /**
   * Retrieves a specific draft by its ID.
   * Ensures the draft belongs to the provided user.
   */
  async getDraftById(draftId: number, userId: number) {
    return prisma.draft.findFirst({
      where: { 
        id: draftId,
        userId 
      },
    });
  }

  /**
   * Updates the generatedContent of a draft.
   * Includes XSS sanitization to prevent malicious injection from the Dashboard.
   */
  async updateDraftContent(draftId: number, userId: number, content: NewsArticleJSON) {
    const draft = await this.getDraftById(draftId, userId);
    
    if (!draft) {
      throw new AppError('Draft not found or does not belong to user.', 404);
    }

    // Strict sanitization: strip ALL HTML tags to prevent XSS
    const sanitizeOptions = {
      allowedTags: [],
      allowedAttributes: {},
    };

    const sanitizedContent: any = {
      titulo: sanitizeHtml(content.titulo || '', sanitizeOptions).trim(),
      resumo: sanitizeHtml(content.resumo || '', sanitizeOptions).trim(),
      corpo: sanitizeHtml((content as any).corpo || '', sanitizeOptions).trim(),
      fonte: sanitizeHtml(content.fonte || '', sanitizeOptions).trim(),
    };

    if (!sanitizedContent.titulo || !sanitizedContent.fonte) {
      throw new AppError('Fields (titulo, fonte) must be provided and cannot be empty.', 400);
    }

    return prisma.draft.update({
      where: { id: draftId },
      data: { 
        generatedContent: sanitizedContent as any
      },
    });
  }

  /**
   * Updates the status of a draft.
   */
  async updateDraftStatus(draftId: number, status: DraftStatus) {
    return prisma.draft.update({
      where: { id: draftId },
      data: { status },
    });
  }

  /**
   * Deletes a draft completely from the database.
   */
  async deleteDraft(draftId: number, userId: number): Promise<void> {
    await prisma.draft.deleteMany({
      where: {
        id: draftId,
        userId: userId
      }
    });
    logger.info(`[draft-service]: Deleted draft ${draftId} for user ${userId}.`);
  }

  /**
   * Enqueues a broadcast for ALL approved drafts to the SELECTED contacts.
   */
  async launchBroadcast(userId: number, contactIds: number[], delaySeconds: number): Promise<void> {
    // 1. Fetch all APPROVED drafts for the user
    const approvedDrafts = await prisma.draft.findMany({
      where: { userId, status: DraftStatus.APPROVED }
    });

    if (approvedDrafts.length === 0) {
      throw new Error('Nenhuma minuta aprovada encontrada para disparo.');
    }

    // 2. Fetch the selected contacts
    const contacts = await prisma.contact.findMany({
      where: {
        id: { in: contactIds },
        userId,
        active: true
      }
    });

    if (contacts.length === 0) {
      throw new Error('Nenhum contato válido selecionado.');
    }

    // 3. For each approved draft, enqueue a broadcast job
    for (const draft of approvedDrafts) {
      await broadcastQueue.add(BROADCAST_QUEUE_NAME, {
        draftId: draft.id,
        userId,
        imagePath: draft.imagePath,
        contacts: contacts.map(c => ({
          id: c.id,
          phoneNumber: c.phoneNumber,
          name: c.name
        })),
        delayMs: delaySeconds * 1000
      });
      logger.info(`[draft-service]: Queued broadcast job for Draft ${draft.id} to ${contacts.length} contacts with ${delaySeconds}s delay.`);
    }
  }

  /**
   * Cancels an ongoing or pending broadcast.
   * - Updates status to CANCELLED in Postgres.
   * - Finds and removes waiting/delayed jobs from BullMQ.
   */
  async cancelBroadcast(draftId: number, userId: number): Promise<void> {
    logger.info(`[draft-service]: Attempting to cancel broadcast for draft ${draftId} by user ${userId}.`);
    
    await this.updateDraftStatus(draftId, DraftStatus.CANCELLED);

    // Attempt to remove waiting/delayed jobs associated with this draft
    // In our architecture, the job data contains the draftId
    try {
      const waitingJobs = await broadcastQueue.getWaiting();
      const delayedJobs = await broadcastQueue.getDelayed();
      
      const allPendingJobs = [...waitingJobs, ...delayedJobs];
      
      for (const job of allPendingJobs) {
        if (job.data && job.data.draftId === draftId && job.data.userId === userId) {
          await job.remove();
          logger.info(`[draft-service]: Removed job ${job.id} from queue for cancelled draft ${draftId}.`);
        }
      }
    } catch (error) {
      logger.error(`[draft-service]: Failed to clean up BullMQ jobs during cancellation: ${(error as Error).message}`);
    }
  }
}

export default new DraftService();
